services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - ./bootstrap/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  pg_data:
