apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  KC_HOSTNAME: {{ .Values.keycloak.hostname | quote }}
  KC_PROXY: {{ .Values.keycloak.proxy | quote }}
  KC_QUARKUS_HTTP_INSECURE_REQUESTS: {{ .Values.keycloak.httpInsecureRequests | quote }}
  KC_DB: {{ .Values.database.vendor | quote }}
  KC_DB_URL: {{ printf "jdbc:postgresql://%s:%v/%s" .Values.database.host (.Values.database.port | toString) .Values.database.name | quote }}
  KC_DB_USERNAME: {{ .Values.database.username | quote }}
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username | quote }}
