apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
  KC_DB_PASSWORD: {{ .Values.database.password | quote }}
